"""added submitted by field

Revision ID: 164f5b43936e
Revises: c3d9861187d
Create Date: 2017-02-20 19:21:24.208944

"""

# revision identifiers, used by Alembic.
revision = '164f5b43936e'
down_revision = 'c3d9861187d'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('submitted_by', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'submitted_by')
    ### end Alembic commands ###
