"""initial migration

Revision ID: c3d9861187d
Revises: None
Create Date: 2015-07-10 08:08:38.032370

"""

# revision identifiers, used by Alembic.
revision = 'c3d9861187d'
down_revision = None

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('link', sa.String(length=200), nullable=True),
    sa.Column('created_on', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('submitted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submission')
    ### end Alembic commands ###
